name: Build and release

on:
  push:
    tags:
      - '*'
      -
env:
  PLUGIN_NAME: "enwikuna-license-manager-client"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: '7.4'
          php_extensions: zip
          dev: no

      - name: Create prepack folder
        run: |
          rm -rf ../prepack/$PLUGIN_NAME
          mkdir -p ../prepack/$PLUGIN_NAME

      - name: Copy content to prepack folder
        run: rsync -rav --exclude=".*" --exclude="composer.*" --exclude="phpcs.xml" --exclude="__MACOSX" . ../prepack/$PLUGIN_NAME

      - name: Create release ZIP artifact
        run: |
          cd ../prepack
          pwd
          zip -r ../$PLUGIN_NAME/$PLUGIN_NAME.zip $PLUGIN_NAME
          pwd
          ls
          cd ../$PLUGIN_NAME
          pwd
          ls

      - name: Upload release ZIP artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PLUGIN_NAME }}
          path: ${{ github.workspace }}/prepack/$PLUGIN_NAME/$PLUGIN_NAME.zip

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: "Release ${{ github.ref_name }} of Enwikuna License Manager Client"
          draft: false
